=== SkoriyVladislav/xml-parsers/src/by/epam/tr/resources/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.tc.com/device"
        xmlns:tns="http://www.epam.tc.com/device">


    <element name="devices">
        <complexType>
            <sequence>
                <element name="device" type="tns:device"
                         minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="device">
        <sequence>
            <element name="name" type="string"/>
            <element name="price" type="double"/>
            <element name="origin" type="string"/>
            <element name="address" type="tns:address"/>
            <element name="critical" type="boolean"/>
        </sequence>
        <attribute name="id" type="int" use="required"/>
    </complexType>

    <complexType name="address_not_full">
        <sequence>
            <element name="country" type="string"/>
            <element name="city" type="string"/>
        </sequence>

        <attribute name="type" use="optional" default="home">
            <simpleType>
                <restriction base="string">
                    <enumeration value="home"/>
                    <enumeration value="work"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>

    <complexType name="address">
        <complexContent>
            <extension base="tns:address_not_full">
                <sequence>
                    <element name="street" type="string"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== SkoriyVladislav/xml-parsers/src/by/epam/tr/resources/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<tc:devices xmlns:tc="http://www.epam.tc.com/device"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.epam.tc.com/device devices.xsd">
    <device id="1">
        <name>Hard disk</name>
        <price>49.99</price>
        <origin>USA</origin>
        <type>zaebis</type>
        <critical>false</critical>
    </device>

    <device id="2">
        <name>Hard disk</name>
        <price>39.99</price>
        <origin>USA</origin>
        <type>not zaebis</type>
        <critical>false</critical>
    </device>
</tc:devices>
